#!/usr/bin/env python3

import rospy

from cv_bridge import CvBridge
from deepface import DeepFace

from sensor_msgs.msg import Image
from deepface_msgs.srv import FacesAnalysisSrv, FacesAnalysisSrvResponse
from deepface_msgs.srv import ImageFacesAnalysis, ImageFacesAnalysisResponse
from deepface_msgs.msg import Emotion, Race, Gender, FaceDetection, FaceAnalysis, FacesAnalysis


class DeepFaceNode():

    def __init__(self):
        print(rospy.get_param_names())
        
        self.cv_bridge = CvBridge()
        
        sub_topic = rospy.get_param("~sub_topic", "sub")
        image_face_srv_topic = rospy.get_param("~image_face_srv_topic", "image_face_srv")
        face_analysis_srv_topic = rospy.get_param("~face_analysis_srv_topic", "face_analysis_srv")

        pub_topic = rospy.get_param("~pub_topic", "pub")
        self.run_race = rospy.get_param("~race_enable", False)
        self.run_emotion = rospy.get_param("~emotion_enable", False)
        self.run_age = rospy.get_param("~age_enable", False)
        self.run_gender = rospy.get_param("~gender_enable", False)
        self.publish_online_analysis = rospy.get_param("publish_online_analysis", True)

        if (self.run_race+self.run_age+self.run_emotion+self.run_gender) == 0:
            rospy.logerr("No outputs enabled. Enabling emotion by default")
            self.run_emotion = True
        
        self.actions = list()
        if self.run_age:
            self.actions.append("age")
        if self.run_emotion:
            self.actions.append("emotion")
        if self.run_gender:
            self.actions.append("gender")
        if self.run_race:
            self.actions.append("race")
            

        self.sub = rospy.Subscriber(sub_topic, Image, self.image_cb, buff_size=1)
        self.face_analysis_pub = rospy.Publisher(pub_topic, FacesAnalysis, queue_size=1)
        self.image_face_analysis_srv = rospy.Service(image_face_srv_topic, ImageFacesAnalysis, self.image_face_analysis_callback)
        self.face_analysis_srv = rospy.Service(face_analysis_srv_topic, FacesAnalysisSrv, self.face_analysis_callback)

    def image_cb(self, msg: Image) -> None:
        
        self.image = self.cv_bridge.imgmsg_to_cv2(msg)
        if self.publish_online_analysis:
            faces_analysis_msg = self.face_analysis(self.image)
            self.face_analysis_pub.publish(faces_analysis_msg)

    def image_face_analysis_callback(self, req):
        
        cv_image = self.cv_bridge.imgmsg_to_cv2(req.image)
        faces_analysis_msgs = self.face_analysis(cv_image)
        
        res = ImageFacesAnalysisResponse()
        res.faces_analysis = faces_analysis_msgs
        res.success = True
        
        return res
    
    def face_analysis_callback(self, req):
        
        image_to_analyse = self.image
        
        res = FacesAnalysisSrvResponse()

        if image_to_analyse is None:
            res.success = False
            return res
        
        faces_analysis_msgs = self.face_analysis(image_to_analyse)
                
        res.faces_analysis = faces_analysis_msgs
        res.success = True
        
        return res
    
    def face_analysis(self, cv_image) -> FacesAnalysis:
        faces_analysis_msg = FacesAnalysis()

        try:
            result = DeepFace.analyze(cv_image, self.actions)
        except Exception as e:
            return faces_analysis_msg

        for face_analysis in result:
            result_msg = FaceAnalysis()

            result_msg.face_detection = FaceDetection()
            result_msg.face_detection.roi.x_offset = max(0,face_analysis['region']['x'])
            result_msg.face_detection.roi.y_offset = max(0,face_analysis['region']['y'])
            result_msg.face_detection.roi.height = face_analysis['region']['h']
            result_msg.face_detection.roi.width = face_analysis['region']['w']
            result_msg.face_detection.confidence = face_analysis['face_confidence']

            if self.run_age:
                result_msg.age = face_analysis['age']

            if self.run_emotion:
                result_msg.dominant_emotion = face_analysis['dominant_emotion']
                for emotion in face_analysis['emotion']:
                    emotion_msg = Emotion()
                    emotion_msg.emotion = emotion
                    emotion_msg.score = face_analysis['emotion'][emotion]
                    result_msg.emotions.append(emotion_msg) 
            
            if self.run_gender:
                result_msg.dominant_gender = face_analysis['dominant_gender']
                for gender, score in face_analysis['gender'].items():
                    gender_msg = Gender()
                    gender_msg.gender = gender
                    gender_msg.score = score
                    result_msg.genders.append(gender_msg)

            if self.run_race:
                result_msg.dominant_race = face_analysis['dominant_race']
                for race, score in face_analysis['race'].items():
                    race_msg = Race()
                    race_msg.race = race
                    race_msg.score = score
                    result_msg.races.append(race_msg)            
            
            faces_analysis_msg.faces_analysis.append(result_msg)
        return faces_analysis_msg

def main(args=None):
    # Start the Server Endpoint
    rospy.init_node("rosbridge_client", anonymous=True)
    node = DeepFaceNode()
    rospy.spin()

if __name__ == "__main__":
    main()
